name: CI/CD Backend Inventario

on:
  push:
    branches: [develop]

jobs:
  ci-validacion:
    name: Validación del código
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Descargar dependencias
        run: go mod download

      - name: Verificar formato del código
        run: go fmt ./...

      - name: Ejecutar build
        run: go build ./...

      - name: Ejecutar tests
        run: go test ./...

  ci-imagen:
    name: Construcción y push de imagen Docker
    needs: ci-validacion
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Autenticarse en Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Docker para usar Artifact Registry
        run: gcloud auth configure-docker southamerica-east1-docker.pkg.dev

      - name: Construir imagen Docker
        run: docker build -t southamerica-east1-docker.pkg.dev/construtem/microservicios-construtem/back-inventario:latest .

      - name: Subir imagen a Artifact Registry
        run: docker push southamerica-east1-docker.pkg.dev/construtem/microservicios-construtem/back-inventario:latest

  cd:
    name: Despliegue Continuo
    needs: ci-imagen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Autenticarse en GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar kubectl
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: construtem
          export_default_credentials: true

      - name: Instalar gcloud y gke-gcloud-auth-plugin
        run: |
          sudo mkdir -p /usr/share/keyrings
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Configurar contexto de kubectl
        run: |
          gcloud container clusters get-credentials construtem-testing \
            --region southamerica-east1 \
            --project construtem

      - name: Aplicar manifiestos de Kubernetes
        run: kubectl apply -f k8s/
